// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByQ82d0TUUnUlrXWNdNWAwYfRUiXWYKuw',
    appId: '1:624736263244:web:24020127bdc5c46a9a28e9',
    messagingSenderId: '624736263244',
    projectId: 'onlyforimages-2e293',
    authDomain: 'onlyforimages-2e293.firebaseapp.com',
    databaseURL: 'https://onlyforimages-2e293-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'onlyforimages-2e293.appspot.com',
    measurementId: 'G-5MWD223N9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqCK6IMgW2uvmKm4pF7KszXP2fdgT_NSA',
    appId: '1:624736263244:android:ea645a815aeea8469a28e9',
    messagingSenderId: '624736263244',
    projectId: 'onlyforimages-2e293',
    databaseURL: 'https://onlyforimages-2e293-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'onlyforimages-2e293.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwxlW6O1KheMcDQErRqg1hdJc43IhqBRo',
    appId: '1:624736263244:ios:0159ead00ef500a09a28e9',
    messagingSenderId: '624736263244',
    projectId: 'onlyforimages-2e293',
    databaseURL: 'https://onlyforimages-2e293-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'onlyforimages-2e293.appspot.com',
    androidClientId: '624736263244-denbpcd8b5ogvvq3t690gehhg82ehc7h.apps.googleusercontent.com',
    iosClientId: '624736263244-d3av40044faoejths299i1biokpjg0uo.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantOwnerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwxlW6O1KheMcDQErRqg1hdJc43IhqBRo',
    appId: '1:624736263244:ios:0159ead00ef500a09a28e9',
    messagingSenderId: '624736263244',
    projectId: 'onlyforimages-2e293',
    databaseURL: 'https://onlyforimages-2e293-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'onlyforimages-2e293.appspot.com',
    androidClientId: '624736263244-denbpcd8b5ogvvq3t690gehhg82ehc7h.apps.googleusercontent.com',
    iosClientId: '624736263244-d3av40044faoejths299i1biokpjg0uo.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantOwnerApp',
  );
}
